encoding: utf-8
# Site settings
course_name: Large-Scale Multimedia Analysis
course_description: "Can a robot watch Youtube to learn about the world? What makes us laugh? How to bake a cake? Why is Kim Kardashian famous? Large-scale multi-media is an incomparable window into our world, with thousands of hours of data available on almost every aspect of our everyday life. The analysis of such data is a unique opportunity to perform deep multi-modal analysis that goes beyond image or video retrieval, speech to text, or other existing tasks. This is a 12-unit class or lab covering fundamentals of large-scale computer vision, audio and speech processing, multi-media files and streaming, multi-modal signal processing, video retrieval, semantics, and text (possibly also: speech, music) generation. "
course_semester: "Fall 2024"

baseurl: "/11-775" # the subpath of your site, e.g. /blog/
url: "https://cmu-mlsp.github.io" # the base hostname & protocol for your site

schoolname: "11-775"
schoolurl: "https://www.lti.cs.cmu.edu/"
twitter_username:

address: |
    Language Technologies Institute
    School of Computer Science
    Carnegie Mellon University
    5000 Forbes Avenue
    Pittsburgh, PA 15213

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
